name: Wake Ping Northstar App

on:
  schedule:
    # run every hour, adjust if you prefer fewer pings
    - cron: '0 * * * *'  # every hour (UTC)
  workflow_dispatch:  # allows manual run
jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Streamlit App
        run: |
          echo "Pinging Northstar app to keep it awake..."
          curl -L --max-time 20 "https://northstar-ecosystem-final-realdata-active-tomstrom26.streamlit.app"
