name: Wake Northstar

on:
  schedule:
    - cron: '20 11 * * *'   # 6:20 AM CT
    - cron: '55 13 * * *'   # 8:55 AM CT
    - cron: '55 15 * * *'   # 10:55 AM CT
    - cron: '55 18 * * *'   # 1:55 PM CT
    - cron: '20 21 * * *'   # 3:20 PM CT
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Hit Streamlit app
        run: |
          curl -fsS -m 20 https://northstar-ecosystem-final-realdata-active-tomstrom26.streamlit.app || true
