name: Wake Ping Northstar App

on:
  schedule:
    # wake 5 minutes before each analysis/draw
    - cron: '25 11 * * *'   # 6:25 AM CT (11:25 UTC)
    - cron: '55 14 * * *'   # 9:55 AM CT (14:55 UTC)
    - cron: '55 16 * * *'   # 11:55 AM CT (16:55 UTC)
    - cron: '55 19 * * *'   # 2:55 PM CT (19:55 UTC)
    - cron: '25 21 * * *'   # 3:25 PM CT (21:25 UTC)
  workflow_dispatch:  # allow manual run

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Streamlit app
        run: |
          echo "🚀 Keeping Streamlit app awake..."
          curl -fsS -m 20 https://northstar-ecosystem-final-realdata-active-tomstrom26.streamlit.app || echo "Ping failed but continuing"
