 [github]
token = "ghp_SHA256:hS2dnOOQVt0+TN7Nb69A34SqpE6yqz5Oqrz2rYxy9N8"
owner = "tomstrom26"
repo = "tomstrom26/northstar_ecosystem_final_realdata_active"
branch = "main"

[email]
smtp_host = "smtp.gmail.com"
smtp_port = 587
smtp_user = "tengstrom2620@gmail.com"
smtp_pass = "vmad wxzc wnnh zixk"
to = "tengstrom2620@gmail.com"
from_addr = "Northstar <tengstrom2620@gmail.com>"
