 [github]
token = "ghp_SHA256:hS2dnOOQVt0+
##############################################
# NORTHSTAR ECOSYSTEM — SECURE SECRETS FILE  #
# This file provides access tokens and creds #
# Auto-loaded by Streamlit during execution. #
##############################################

[github]
# GitHub sync credentials
token   = ""ghp_SHA256:hS2dnOOQVt0+TN7Nb69A34SqpE6yqz5Oqrz2rYxy9N8""
owner   = "tomstrom26"
repo    = "tomstrom26/northstar_ecosystem_final_realdata_active"
branch  = "main"

[email]
# Gmail SMTP settings for daily reports + alerts
smtp_host = "smtp.gmail.com"
smtp_port = 587
smtp_user = "tengstrom2620@gmail.com"
smtp_pass = "vmad wxzc wnnh zixk"      # your app password
to         = "tengstrom2620@gmail.com"
from_addr  = "Northstar <tengstrom2620@gmail.com>"

[scheduler]
# All automated task times — CST (Central Time)
# These are your current production schedules:
n5_postdraw_time = "07:00"       # Daily post-draw
g5_postdraw_time = "07:00"       # Mon/Wed/Fri post-draw
g5_predraw_time  = "14:00"       # Mon/Wed/Fri pre-draw
pb_postdraw_time = "07:00"       # Tue/Thu/Sun post-draw
pb_predraw_time  = "14:00"       # Mon/Wed/Sat pre-draw
daily_full_run   = "05:00"       # Master orchestrator (full cycle)

[mnlottery]
# Official MN Lottery draw sources
n5_url = "https://www.mnlottery.com/games/northstar-cash"
g5_url = "https://www.mnlottery.com/games/gopher-5"
pb_url = "https://www.mnlottery.com/games/powerball"

[system]
# Internal system flags
build_version = "v3.0-realdata-refined"
use_cache = true
allow_proxy_fallback = true
auto_update_sources = true
notify_email = true
debug_mode = false

